var expect = require('chai').expect
    , PelcoD = require('../pelcod')
    , MemoryStreams = require('memory-streams')

describe('PelcoD', function(){

    describe("#PelcoD", function() {
        it('should have default values', function(){
            var pelcod = new PelcoD({}, {})
            expect(pelcod).to.be.a('object')
            expect(pelcod).to.have.ownProperty('options')
            expect(pelcod.options).to.be.a('object')
            expect(pelcod.bytes).to.be.a('object')
        })
        it('should accept options', function(){
            var addrs = [1,2]
            var pelcod = new PelcoD({}, {
                addrs: addrs,
                defaultAddr: 0x02
            })
            expect(pelcod.options.defaultAddr).to.equal(0x02)
            expect(pelcod.options.addrs).to.equal(addrs)
        })

    })

    describe("Exist functions", function() {
        var pelcod = new PelcoD({}, {})
        it('should have its functions', function(){
            expect(pelcod.setAddress).to.be.a('function')
            expect(pelcod.setAddrDefault).to.be.a('function')
            expect(pelcod.setPanSpeed).to.be.a('function')
            expect(pelcod.setTiltSpeed).to.be.a('function')
            expect(pelcod.up).to.be.a('function')
            expect(pelcod.down).to.be.a('function')
            expect(pelcod.left).to.be.a('function')
            expect(pelcod.right).to.be.a('function')
            expect(pelcod.focusNear).to.be.a('function')
            expect(pelcod.focusFar).to.be.a('function')
            expect(pelcod.irisOpen).to.be.a('function')
            expect(pelcod.irisClose).to.be.a('function')
            expect(pelcod.zoomIn).to.be.a('function')
            expect(pelcod.zoomOut).to.be.a('function')
            expect(pelcod.sendSetPreset).to.be.a('function')
            expect(pelcod.sendGotoPreset).to.be.a('function')
            expect(pelcod.sendClearPreset).to.be.a('function')
            expect(pelcod.stop).to.be.a('function')
            expect(pelcod.send).to.be.a('function')  
        })
    })

    describe("Config Commands", function(){
        var pelcod = new PelcoD({}, {})
        it('should set #setAddress', function(){
            pelcod.setAddress(0x05)
            expect(pelcod.bytes.getAddress().get()).to.be.equal(0x05)
        })
    })

    describe("Start Command Set", function(){
        it("should #setPanSpeed works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.setPanSpeed(-50)
            expect(pelcod.bytes.getData1().get()).to.be.equal(0)
            pelcod.setPanSpeed(0xFFF)
            expect(pelcod.bytes.getData1().get()).to.be.equal(0)
            pelcod.setPanSpeed(0x10)
            expect(pelcod.bytes.getData1().get()).to.be.equal(0x10)
        })
        it("should #setTiltSpeed works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.setTiltSpeed(-50)
            expect(pelcod.bytes.getData2().get()).to.be.equal(0)
            pelcod.setTiltSpeed(0xFFF)
            expect(pelcod.bytes.getData2().get()).to.be.equal(0)
            pelcod.setTiltSpeed(0x10)
            expect(pelcod.bytes.getData2().get()).to.be.equal(0x10)
        })
        it("should #up works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.up(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x08)
            pelcod.up(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0)
        })
        it("should #down works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.down(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x10)
            pelcod.down(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0)
        })
        it("should #left works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.left(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x04)
            pelcod.left(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0)
        })
        it("should #right works", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.right(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x02)
            pelcod.right(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0)
        })
        it("should invert #down and #up", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.up(true)
            pelcod.down(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x10)
            pelcod.down(true)
            pelcod.up(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x08)
        })
        it("should invert #left and #right", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.left(true)
            pelcod.right(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x02)
            pelcod.right(true)
            pelcod.left(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x04)
        })
        it("should work with #up and #left or #right", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.up(true)
            pelcod.left(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0xC)
            pelcod.right(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0xA)
        })
        it("should work with #down and #left or #right", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.down(true)
            pelcod.left(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x14)
            pelcod.right(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x12)
        })
        it("should work with #focusNear", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.focusNear(true)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x1)
            pelcod.focusNear(false)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x0)
        })
        it("should work with #focusFar", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.focusFar(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x80)
            pelcod.focusFar(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x00)
        })
        it("should work with #zoomIn", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.zoomIn(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x20)
            pelcod.zoomIn(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x00)
        })
        it("should work with #zoomOut", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.zoomOut(true)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x40)
            pelcod.zoomOut(false)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x00)
        })
        it("should work with #irisOpen", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.irisOpen(true)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x02)
            pelcod.irisOpen(false)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x00)
        })
        it("should work with #irisClose", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.irisClose(true)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x04)
            pelcod.irisClose(false)
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x00)
        })
        it("should work with #stop", function(){
            var pelcod = new PelcoD({}, {})
            pelcod.down(true)
            pelcod.left(true)
            pelcod.setPanSpeed(0x10)
            pelcod.setTiltSpeed(0x10)
            pelcod.irisOpen(true)
            pelcod.focusNear(true)
            pelcod.zoomIn(true)
            pelcod.stop()
            expect(pelcod.bytes.getCom1().get()).to.be.equal(0x0)
            expect(pelcod.bytes.getCom2().get()).to.be.equal(0x0)
            expect(pelcod.bytes.getData1().get()).to.be.equal(0x0)
            expect(pelcod.bytes.getData2().get()).to.be.equal(0x0)
        })
        it("should write to a stream (memory-stream)", function(){
            var stream = new MemoryStreams.WritableStream()
            var pelcod = new PelcoD(stream, {})
            pelcod.bytes.clearAll(false)
            pelcod.setAddress(1);
            pelcod.up(true);
            pelcod.setTiltSpeed(0x3F);
            pelcod.send()
            expect(stream.toBuffer().length).to.be.equal(7)
        })
        it("should not write to a non-writable stream (memory-stream)", function(){
            // This test is for code coverage stats. There is no output to check
            // console.log error will be generated
            var stream = new MemoryStreams.ReadableStream()
            var pelcod = new PelcoD(stream, {})
            pelcod.bytes.clearAll(false)
            pelcod.setAddress(1);
            pelcod.up(true);
            pelcod.setTiltSpeed(0x3F);
            pelcod.send()
            expect(1).to.be.equal(1)
        })
        it("should send valid data and valid checksum", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.bytes.clearAll(false)
            pelcod.setAddress(1);
            pelcod.up(true);
            pelcod.setTiltSpeed(0x3F);
            pelcod.send()
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x01)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x08)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x3F)
            expect(stream.toBuffer()[6]).to.be.equal(0x48)
        })
        it("should test checksum mod 256", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.bytes.clearAll(false)
            pelcod.setAddress(240);
            pelcod.up(true);
            pelcod.setTiltSpeed(0x3F);
            pelcod.send()
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(240)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x08)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x3F)
            expect(stream.toBuffer()[6]).to.be.equal(0x37)
        })
    })

    describe("Extends Command Set", function(){
        it("should send Goto Preset", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(0x2A)
            pelcod.sendGotoPreset(5)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x2A)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x07)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x05)
            expect(stream.toBuffer()[6]).to.be.equal(0x36)
        })
        it("should send Store Preset", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(0x2B)
            pelcod.sendSetPreset(2)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x2B)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x03)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x02)
            expect(stream.toBuffer()[6]).to.be.equal(0x30)
        })
        it("should send Clear Preset", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(0x2B)
            pelcod.sendClearPreset(2)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x2B)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x05)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x02)
            expect(stream.toBuffer()[6]).to.be.equal(0x32)
        })
        it("should send Set Auxiliary", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(16)
            pelcod.sendSetAux(5)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x10)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x09)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x05)
            expect(stream.toBuffer()[6]).to.be.equal(0x1E)
        })
        it("should send Clear Auxiliary", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(16)
            pelcod.sendClearAux(5)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x10)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x0B)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x05)
            expect(stream.toBuffer()[6]).to.be.equal(0x20)
        })
        it("should send Set Zoom Speed", function(){
            var stream = new MemoryStreams.WritableStream() 
            var pelcod = new PelcoD(stream, {})
            pelcod.setAddress(1)
            pelcod.sendSetZoomSpeed(2)
            expect(stream.toBuffer()[0]).to.be.equal(0xFF)
            expect(stream.toBuffer()[1]).to.be.equal(0x01)
            expect(stream.toBuffer()[2]).to.be.equal(0x00)
            expect(stream.toBuffer()[3]).to.be.equal(0x25)
            expect(stream.toBuffer()[4]).to.be.equal(0x00)
            expect(stream.toBuffer()[5]).to.be.equal(0x02)
            expect(stream.toBuffer()[6]).to.be.equal(0x28)
        })
    });
})
